Backend: Vivado
ClockPeriod: 5
HLSConfig:
  Model:
    Precision: ap_fixed<16,6>
    ReuseFactor: 1
IOType: io_parallel
KerasH5: Model.h5
OutputDir: SMD_M
ProjectName: myproject
Stamp: CAdBaB7C
XilinxPart: xcku115-flvb2104-2-i
